i3-config:
	cat ~/config/i3/config                >  config.out
	cat ~/config/theme/i3                >> config.out
	cat ~/config/keybinds/main           >> config.out
	cat ~/config/keybinds/media          >> config.out
	cat ~/config/keybinds/workspaces     >> config.out
	cat ~/config/keybinds/screenshot     >> config.out
